- name: Get official ELRS artifacts
  run: |
    bash get_artifacts.sh

- name: Patch NewPower target
  run: |
    node scripts/patch-targets.cjs

- name: Install dependencies
  run: |
    npm install

- name: Build
  run: |
    npm run build
